{% set name = "xtensor" %}
{% set version = "0.2.2" %}
{% set sha256 = "00cf4e73d9166faa9183c993d0f050376eb3901166df95d933b67c790bbcc147" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://github.com/QuantStack/xtensor/archive/{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
  number: 0

test:
  requires:
    - gtest
    - cmake

  commands:
    - test -d ${PREFIX}/include/xtensor  # [unix]
    - test -f ${PREFIX}/include/xtensor/xarray.hpp  # [unix]
    - if exist %PREFIX%\include\xtensor\xarray.hpp (exit 0) else (exit 1)  # [win]

about:
  home: http://quantstack.net/xtensor
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'The C++ tensor algebra library'
  description: 'Multi dimensional arrays with broadcasting and lazy computing'
  doc_url: http://xtensor.readthedocs.io
  dev_url: https://github.com/QuantStack/xtensor

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
