{% set name = "xtensor" %}
{% set version = "0.9.0" %}
{% set sha256 = "41d7234c6c17389a346f669e6834a21ed72fde39c539d7186037a8ae5e3a05bf" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/QuantStack/xtensor/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py<36]

requirements:
  build:
    - python
    - toolchain
    - cmake

test:
  commands:
    - test -d ${PREFIX}/include/xtensor  # [unix]
    - test -f ${PREFIX}/include/xtensor/xarray.hpp  # [unix]
    - test -f ${PREFIX}/share/cmake/xtensor/xtensorConfig.cmake  # [unix]
    - test -f ${PREFIX}/share/cmake/xtensor/xtensorConfigVersion.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\xtensor\xarray.hpp (exit 0) else (exit 1)  # [win]
    - if exist %PREFIX%\share\cmake\xtensorConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %PREFIX%\share\cmake\xtensorConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://quantstack.net/xtensor
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'The C++ tensor algebra library'
  description: 'Multi dimensional arrays with broadcasting and lazy computing'
  doc_url: http://xtensor.readthedocs.io
  dev_url: https://github.com/QuantStack/xtensor

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
