travis:
  secure:
    BINSTAR_TOKEN: fNnkBTpbzwyiGSBCm7JptDgkgQQNGoFbDPU3OyW0lyWZ+OMuO4+R1eCZRHmZtRObmkzcmuJSAwLAtt/+TcuAWOB/eldcHq9/LKIyvAVIzoXO+VQBGpnvIP61jJG2iJDflPSxb2+qSRBw1/9QE4PhDur4vRHsqvDAimRnqkHBT7NMoBWgMb6wH4HSMmpl2LFcKFluJN6pbMNqHfdcnGzEtupzTDBYUd1ltKJrM/UV2xxhuiQ3s7ClH/HSTrkUFxJqBCD5KinjcM4I9qC1cZxD0jRKS114oNltNcwSjY5Rjsp2kZiRQwMR9xdAq3QJ3eytL3+HDUw9ulscH9z9RLnqp+kJc03zX0oX3g6df6EcWH+mg7PYzMKuJ8INMzeXiD1ZbodPfw0orTIRiO6VBHPdwR0iUSzu83DDQicV4/22g6oGVsFupaBzt7YHwpgGUESRPH29+PRWt5s4tr+EwkNzO1gGPmHUe/BW3c7Tu6xvCC8J8lxAI4+i3oAY4ROQImhJj6vGIYkHoBVZfa/ubJILl3BudmYTj1yYi1flCN1W5BKqzPvAKEWUsq18z0y9QNrDA5iWdjLAU9tHN/1nApVxlyLnA54SPOMXdL4kk5cS3q6h3LCoPJfhSkSP5BD9tE8OPBmgrCIU/BvETL/KBuEc12LaFp5sKopK1Ie3nZ5FcZo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
