travis:
  secure:
    BINSTAR_TOKEN: uS3OduYxCFpM5Hu85iRn9yRxHFgB601H5z66kXIGSONlTnQwJ3oYG8UNjKa0JjPos++Z6O8frpykga4FFWA6RntqWDVYsq6N7gpNgK4KnlJb3tHT4omba/JZbgzO8ahWUPoq1s+YSzRX66RdPIbViZPEbT4vu/64YE4y5jtuL1UyC2OOGDOmjCIgPGqyn5cAbFuhWd8uffn3m3Pfj0oX0ZwPC3dmJ92GMkD6wqqWDUE9n1Yo8cYqekBbUan18oLjqeXE5BghH9qTIshNSkGaM/txTid6EmhXZGOtuXXFuqa9Rka6fpFd7IFxk5TmOxZCHwIMj6UCuEGRP+G1vbXPCwSX1JOx65cXYtIGA0ISJ3sGVnEOL9kwAZj5/YFVEWDZEXEQ1xg9cLITz+0Koip3T8eXqWsVYFYADCqc1z/5LrBCZuUJ1dF/ZWJYkaXXGDgpgOeGIU65zMgd8ghRsbzpFXebHuEu1ou9O9pMcdALxStuH4DcwQ7vLE/L/lweoxYvB37L8rmVWOAOv6WHeLN7XGxervfGBjnRDbz/2+N1/effXHd0JL+SfYmM6zFLmGpGuTTbK8siukJe/j3HQ5Lg9cyUfh9/Td2ICTrUciJI8PhVCI4cqvkJmgOs4iZWn6SRaY0FMWG5n/pwnLn4XJXt7KfYzWeikQHHW+BIai8pD/o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
